# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {Common-41} -limit 4294967295
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/verilogLab/lab2/lab2.cache/wt [current_project]
set_property parent.project_path D:/verilogLab/lab2/lab2.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  D:/verilogLab/lab2/lab2.srcs/sources_1/new/TwoChoseOneDF.v
  D:/verilogLab/lab2/lab2.srcs/sources_1/new/TwoChOneSt.v
  D:/verilogLab/lab2/lab2.srcs/sources_1/new/TwoChOneBh.v
  D:/verilogLab/lab2/lab2.srcs/sources_1/new/ThreeChOne.v
  D:/verilogLab/lab2/lab2.srcs/sources_1/new/_3To8_Translate.v
}
synth_design -top TwoChOneSt -part xc7a100tcsg324-1
write_checkpoint -noxdef TwoChOneSt.dcp
catch { report_utilization -file TwoChOneSt_utilization_synth.rpt -pb TwoChOneSt_utilization_synth.pb }
