# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {Common-41} -limit 4294967295
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/verilogLab/lab4/lab4.cache/wt [current_project]
set_property parent.project_path D:/verilogLab/lab4/lab4.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  D:/verilogLab/lab4/lab4.srcs/sources_1/new/register.v
  D:/verilogLab/lab4/lab4.srcs/sources_1/new/ram.v
  D:/verilogLab/lab4/lab4.srcs/sources_1/new/mux_21.v
  D:/verilogLab/lab4/lab4.srcs/sources_1/new/full_adder.v
  D:/verilogLab/lab4/lab4.srcs/sources_1/new/comparator.v
  D:/verilogLab/lab4/lab4.srcs/sources_1/new/datapath.v
}
synth_design -top datapath -part xc7a100tcsg324-1
write_checkpoint -noxdef datapath.dcp
catch { report_utilization -file datapath_utilization_synth.rpt -pb datapath_utilization_synth.pb }
